---
abstract: 'Simplex Algorithm Implementation using Tucker Tableau'
author:
  - 'Mateu X Hunter'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Simplex
no_index:
  directory:
    - inc
    - t
requires:
  Class::MethodMaker: 0
  HTML::Table: 0
  HTML::TreeBuilder: 0
  Math::Cephes::Fraction: 0
  PDL: 0
  Readonly: 0
  Tie::File::AsHash: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.24
