---
abstract: 'Simplex Algorithm Implementation using Tucker Tableaux'
author:
  - 'mateu - Mateu X. Hunter (cpan:MATEU) <hunter@missoula.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Simplex
no_index:
  directory:
    - t
    - inc
requires:
  Math::BigRat: 0
  Math::Cephes::Fraction: 0
  Moo: 0
  MooX::Types::MooseLike: 0.16
  PDL: 0
  PDL::Lite: 0
  namespace::clean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Algorithm-Simplex
  repository: git://github.com/mateu/Algorithm-Simplex.git
version: 0.43
